(define (domain logistics)
    (:requirements :conditional-effects :disjunctive-preconditions :equality :negative-preconditions :strips :typing :universal-preconditions)
    (:types city location package plane truck)
    (:predicates (package-at ?p - package ?l - location)  (plane-at ?a - plane ?l - location)  (plane-has-package ?a - plane ?p - package)  (truck-at ?t - truck ?l - location)  (truck-has-package ?t - truck ?p - package))
    (:action drive_truck
        :parameters (?t - truck ?l1 - location ?l2 - location ?p - package ?c - city)
        :precondition (and (truck-at ?t ?l1) (not (truck-at ?t ?l2)) (package-at ?p ?l1))
        :effect (and (not (truck-at ?t ?l1)) (truck-at ?t ?l2))
    )
     (:action fly_airplane
        :parameters (?a - plane ?from - location ?to - location ?p - package)
        :precondition (and (plane-at ?a ?from) (not (plane-has-package ?a ?p)))
        :effect (and (not (plane-at ?a ?from)) (plane-at ?a ?to))
    )
     (:action load_airplane
        :parameters (?p - package ?a - plane ?l - location)
        :precondition (and (package-at ?p ?l) (plane-at ?a ?l) (not (plane-has-package ?a ?p)))
        :effect (and (not (package-at ?p ?l)) (plane-has-package ?a ?p))
    )
     (:action load_truck
        :parameters (?p - package ?t - truck ?l - location)
        :precondition (and (package-at ?p ?l) (truck-at ?t ?l))
        :effect (and (not (package-at ?p ?l)) (truck-has-package ?t ?p))
    )
     (:action unload_airplane
        :parameters (?p - package ?a - plane ?l - location)
        :precondition (and (plane-at ?a ?l) (plane-has-package ?a ?p))
        :effect (and (not (plane-has-package ?a ?p)) (package-at ?p ?l))
    )
     (:action unload_truck
        :parameters (?t - truck ?p - package ?l - location)
        :precondition (and (truck-at ?t ?l) (truck-has-package ?t ?p))
        :effect (and (not (truck-has-package ?t ?p)) (package-at ?p ?l))
    )
)